### ISSUE TITLE
Inductive Models Question

### ISSUE THREAD

**Issue by AlexMRuch** [zjukg/NeuralKG#1]
Really excited to try out this library! I was curious if any of the built-in models are inductive and able to generate embeddings for nodes that are new to networks?

**Comment by chenxn2020** [comment]
Thanks for your interest in our work!  Actually, the models we currently include only support transductive reasoning, and we will continue to expand our model library and reproduce those models for inductive learning.

**Comment by wencolani** [comment]
Hi Alex, we have released NeuralKG-ind (https://github.com/zjukg/NeuralKG/tree/ind) for inductive knowledge graph representation learning. Welcome to try ;)

**Comment by AlexMRuch** [comment]
Thanks so much for letting me know! Excited to check it out!
