### ISSUE TITLE
怎么提取embedding呢？

### ISSUE THREAD

**Issue by XiangtaiKong** [zjukg/NeuralKG#14]
尊敬的作者：
      您好！
      我是涉足KG的一位菜鸟，认为您的这份工作具有非常非常重要的意义！
      想请问一下，如果想获得不同KGE方法获得的embedding，请问需要怎样修改main.py呢？期待您的回复，不胜感激！

**Comment by Modberge** [comment]
您好，想要获取模型的embedding数据不需要更改main.py文件。每轮验证完成后，NeuralKG会在主目录下的'output'文件夹按照模型类别自动生成当前实验验证效果最好的checkpoint。它包含了实验的基本信息以及模型的embedding，您可以通过pytorch的load函数加载模型获取这些信息。

**Comment by XiangtaiKong** [comment]
好的，明白了！谢谢您的回复和详细讲解！
