### ISSUE TITLE
demo问题，验证结果，杭州市rank为9 与 readme中不同？

### ISSUE THREAD

**Issue by zyxdSTU** [zjukg/NeuralKG#16]
有个问题，demo数据集里面，test和valid内容相同，为什么我运行python demo.py时，最终验证结果 杭州市 rank为9.
理论上不是应该更靠前吗， 是和定义的loss函数相关吗？(虽然demo是个小例子）

**Comment by wencolani** [comment]
你好，感谢关注NeuralKG～
1. test和valid内容相同：我们设计demo的目的主要是方便快速展示NeuralKG是如何运行的，因此没有保证test和valid不同；
2. 最终验证结果杭州市的rank为9：demo数据集很小，模型对于对于参数设置和训练情况都比较敏感，跑出来的结果波动会比较大。由于测试样本只有1个，也不具有统计意义，如果确实想测试模型效果，建议在比较大的标准数据集上进行测试；
3. 定义的loss函数是否会影响预测结果：一般会有影响，但影响如何需要再较大的数据集上进行验证。

**Comment by zyxdSTU** [comment]
> 你好，感谢关注NeuralKG～
> 
> 1. test和valid内容相同：我们设计demo的目的主要是方便快速展示NeuralKG是如何运行的，因此没有保证test和valid不同；
> 2. 最终验证结果杭州市的rank为9：demo数据集很小，模型对于对于参数设置和训练情况都比较敏感，跑出来的结果波动会比较大。由于测试样本只有1个，也不具有统计意义，如果确实想测试模型效果，建议在比较大的标准数据集上进行测试；
> 3. 定义的loss函数是否会影响预测结果：一般会有影响，但影响如何需要再较大的数据集上进行验证。

好的，了解。
