### ISSUE TITLE
按照指示配置完所需库，但无法执行demo.py

### ISSUE THREAD

**Issue by AIR-hl** [zjukg/NeuralKG#21]
由于本机显卡原因，pytorch为1.10.0的GPU版，其余库均按指示要求配置，运行demo.py出现如下问题
![image](https://user-images.githubusercontent.com/66808901/226160868-b96618a3-1de3-4076-b06f-e6bf4d2d5d2c.png)

**Comment by Modberge** [comment]
你好，目前截图的报错信息似乎并不完整，能否提供完整的异常信息呢？

**Comment by AIR-hl** [comment]
![image](https://user-images.githubusercontent.com/66808901/226165481-8230ee06-aeda-4727-ab02-221886addebe.png)
没事可以不用劳烦了，Colab上的示例可以正常运行，我可以尝试用Colab完成我的工作🙇‍

**Comment by hmy11111** [comment]
您好，我也同样遇到配置完环境后无法成功运行demo.py的问题，我的报错如下：
![image](https://user-images.githubusercontent.com/112597451/230288071-323e285c-91e8-4f9f-a456-b40aa7138629.png)

**Comment by AIR-hl** [comment]
可能是你的windows系统编码问题，不过我还是建议你直接使用colab，NeuralKG的提供的colab示例是可以正常使用

**Comment by hmy11111** [comment]
> 
好的，谢谢您，我尝试一下

**Comment by hmy11111** [comment]
很抱歉来麻烦您，我还是想询问下以上编码报错有没有什么方法可以解决呢

**Comment by yjq12** [comment]
> 很抱歉来麻烦您，我还是想询问下以上编码报错有没有什么方法可以解决呢

您好 我用windows编译也遇见了同样的问题， 请问您最后解决了吗？

**Comment by yjq12** [comment]
> 由于本机显卡原因，pytorch为1.10.0的GPU版，其余库均按指示要求配置，运行demo.py出现如下问题 ![image](https://user-images.githubusercontent.com/66808901/226160868-b96618a3-1de3-4076-b06f-e6bf4d2d5d2c.png)

在TransE_demo_kg.yaml中将num_workers值改为0
![eb62f449c9622ab873ae22182470250](https://user-images.githubusercontent.com/115932061/236617254-3c304e71-fbdb-4d05-9a1f-7973001ed164.png)

**Comment by yjq12** [comment]
> > 很抱歉来麻烦您，我还是想询问下以上编码报错有没有什么方法可以解决呢
> 
> 您好 我用windows编译也遇见了同样的问题， 请问您最后解决了吗？

已经解决。打开文件时加上encoding=’utf-8‘
![4cb13cd43c058dc8c7e7bae50a41fdf](https://user-images.githubusercontent.com/115932061/236617352-0d196806-1718-476d-b2fa-9303210ed0b6.png)
![6f27877474646cd848fb6a095f71a52](https://user-images.githubusercontent.com/115932061/236617406-74f95376-4b31-417a-a0e1-1edb4b53c177.png)
![e2db6207910ad20a31d4332c1fd5548](https://user-images.githubusercontent.com/115932061/236617413-ac761886-aab7-41a4-b5ed-e6e988552a0b.png)

**Comment by yjq12** [comment]
此外 使用windows系统可能还会出现文件名无效的问题：
![0a7f5d7ba4c5e971b9d77bf1bdf9eda](https://user-images.githubusercontent.com/115932061/236617477-4006789a-6986-4d70-8ade-d066173a9ccb.png)
在demo.py中将文件名Eval|mrr改为Eval_mrr（不能有|）：
![fc8ae497240416932facd709559d501](https://user-images.githubusercontent.com/115932061/236617499-59a4d5d9-d433-484d-8727-1810e9c158c1.png)
