### ISSUE TITLE
保存预测三元组

### ISSUE THREAD

**Issue by jenfung** [zjukg/NeuralKG#26]
你好！请问验证、测试阶段怎么把预测的三元组都输出保存呢？有直接的方法入口吗？

**Comment by hzwy3c** [comment]
您好！

您说的这个目前暂时没有直接的方法入口，但是您可以根据自己需要的格式对triple进行输出或保存，以KGE模型为例，包含tirple数据的batch的流向是Sampler->KGELitModel->link_prediction，您可以在这三步中的任何一步对验证、测试的数据进行输出或保存。
