### ISSUE TITLE
colab示例demo无法运行

### ISSUE THREAD

**Issue by AIR-hl** [zjukg/NeuralKG#28]
示例无任何更改，最后一个单元格执行出现如下错误
![image](https://user-images.githubusercontent.com/66808901/231709745-f02be153-3264-43d0-a130-4d1eb29825a0.png)

**Comment by mingyangligithub** [comment]
You need to install the correct version of PyTorch == 1.9.1

**Comment by AIR-hl** [comment]
已解决，感谢
