### ISSUE TITLE
can‘t run main.py successfully

### ISSUE THREAD

**Issue by hmy11111** [zjukg/NeuralKG#29]
您好，我已在colab上成功安装环境并成功运行demo.py示例，但是无法成功运行main.py文件和script中的sh文件。运行main.py报错如下：
![image](https://user-images.githubusercontent.com/112597451/232775390-3dab745c-ad37-4fac-9fbb-b7d51199613a.png)

另外，我想请问一下，我想在colab中运行script中的sh文件，所需要的命令是什么呢？因为我一直运行不通，我想看看是否是我的命令输入有误

**Comment by hzwy3c** [comment]
您好，非常感谢您对我们工作的关注！

1. 从报错来看是没有设置self.args.max_epochs，导致它的值为NoneType。因为在main.py中没有设置默认的max_epochs值，所以需要您从命令行参数中显示添加其对应的值（具体可以参考sh文件，其中列举了每个模型需要设置的相关参数）。

2. 我不清楚您运行sh文件的方式和报错是怎样的，如果你将Neuralkg源码下载到了你的文件中，那么可以进入Neuralkg目录下，使用`sh ./scripts/your-sh`命令运行（参考README中的Training版块）。如果没有下载源码的话，你可以查看我们的sh文件，参考里面的命令行写法（这个会比较麻烦）。

希望我的回答能对您有所帮助！
