### ISSUE TITLE
模型是否存在early stop

### ISSUE THREAD

**Issue by Nokeli** [zjukg/NeuralKG#30]
我是用您提供的脚本TransE_FB.sh,发现只指定了MAX_EPOCHS=5000,我想问下是否存在early stop参数来控制模型训练

**Comment by Modberge** [comment]
您好，在NeuralKG中可以通过调整CHECK_PER_EPOCH参数和EARLY_STOP_PATIENCE参数来设置模型early_stop提前中止，模型会在每次evaluate过程中记录主要评估指标，并保存当前训练过程中出现的最好结果，同时模型会评估指标连续下降时中止训练。实际上绝大多数默认脚本运行时都会进行提前中止，而不是在MAX_EPOCHS时中止。希望这会对你有所帮助。
