### ISSUE TITLE
windows平台上CPU占用和磁盘读写异常

### ISSUE THREAD

**Issue by Necro1yte** [zjukg/NeuralKG#33]
你好，我在windows平台上运行CCKS数据集的Grail.sh，第一轮训练速度非常快，发现第二轮开始训练速度和CPU占用和磁盘读写都不太正常。请问有可能是什么原因？感谢解答

<img width="770" alt="a57bd86a7b822c67988a1b0f967aa3f" src="https://github.com/zjukg/NeuralKG/assets/44884760/dd5a9576-a732-4261-a6a0-c53541d9f57b">
<img width="854" alt="ad8074fa98a54149b48beb6f657906f" src="https://github.com/zjukg/NeuralKG/assets/44884760/7cb3ad1e-6d71-4285-b17b-b9a5535a0dc2">

**Comment by hzwy3c** [comment]
您好，

这个第一个进度条是训练集中sample负样本，第二个进度条是验证集中sample负样本，第三个进度条是训练集中sample子图，也就是说到这里还未开始训练。同时sample负样本也比sample子图速度要快很多同时内存消耗也很少，所以第一个进度条相比第三个进度条速度快很多。
