### ISSUE TITLE
ccks参数不可用

### ISSUE THREAD

**Issue by zkeykyb** [zjukg/NeuralKG#35]
![截屏2023-07-04 20 41 03](https://github.com/zjukg/NeuralKG/assets/84625485/3ceaff93-47d8-430f-8670-94b90872f769)
在跑sh scripts/CCKS/Grail.sh的时候出现main.py: error: unrecognized arguments: --ccks False的错误，当单独在 main.py添加parser = setup_parser()  # 设置参数
    args = parser.parse_args()
    print(args.ccks)
时，出现
Traceback (most recent call last):
  File "main.py", line 188, in <module>
    print(args.ccks)
AttributeError: 'Namespace' object has no attribute 'ccks'
请问该如何解决？

**Comment by hzwy3c** [comment]
您好，

我们暂时还未将--ccks这个参数放到我们的neuralkg_ind库中，所以您无法通过库直接使用这个参数，您可以在main.py最上方添加以下代码，使本地的neuralkg-ind目录优先于其他目录被import检查。
`import sys
sys.path.insert(0,"./src")`

其他一些细节可以参考[README_CCKS.md](https://github.com/zjukg/NeuralKG/blob/ind/README_CCKS.md)

**Comment by hzwy3c** [comment]
您好，

我们暂时还未将--ccks这个参数放到我们的neuralkg_ind库中，所以您无法通过库直接使用这个参数，您可以在main.py最上方添加以下代码，使本地的neuralkg-ind目录优先于其他目录被import检查。
`import sys`
`sys.path.insert(0,"./src")`

其他一些细节可以参考[README_CCKS.md](https://github.com/zjukg/NeuralKG/blob/ind/README_CCKS.md)

**Comment by zkeykyb** [comment]
感谢回复！问题已解决。

**Comment by hzwy3c** [comment]
不客气，感谢您对我们工作的关注，接下来如遇任何问题请尽管提问。
