### ISSUE TITLE
执行脚本出现错误

### ISSUE THREAD

**Issue by LiuMingwu** [zjukg/NeuralKG#36]
你好，我在使用sh ./scripts/CCKS/Grail.sh指令时，过程中碰到以下问题，请问应该怎么解决？
![image](https://github.com/zjukg/NeuralKG/assets/37980561/acc1c76c-8c41-4d03-ae16-6bf76c374694)
![image](https://github.com/zjukg/NeuralKG/assets/37980561/4edbecad-7bf9-4364-97a2-e5d833068428)

**Comment by hzwy3c** [comment]
您好，

看报错应该是与num_workers有关，这个超参的大小是与不同机器的cpu相关的，您可以尝试将Grail.sh里面的num_workers设置为16或者更小。
