### ISSUE TITLE
main函数中似乎有路径错误

### ISSUE THREAD

**Issue by shannon-paul** [zjukg/NeuralKG#37]
我正在尝试执行CCKS中的Grail脚本，但是在main函数中这几行似乎是错误的
![image](https://github.com/zjukg/NeuralKG/assets/56437396/8c650346-ac70-438b-80aa-b5ebca2d590d)
这里的model_checkpoint.best_model_path是空值，我按照README_CCKS中的流程尝试跑一个epoch，会报以下错误
![image](https://github.com/zjukg/NeuralKG/assets/56437396/a09e2dff-d03d-41c1-bca3-ede2cc0f9da7)
我检查了main中的代码逻辑，发现这里似乎应该改为model_checkpoint.dirpath，不知道我的想法是否正确？谢谢！

**Comment by hzwy3c** [comment]
您好，

非常感谢您对我们提出的宝贵建议，这里面的`best_model_path`是pytorch_lightning框架中封装好的用法，用来检索最佳checkpoint的路径，所以在main.py里面用`best_model_path`是没问题的，dirpath只是checkpoint所在的目录路径。您在跑一个epoch的时候`model_checkpoint.best_model_path`是空值是因为脚本里面的`check_per_step`/`check_per_epoch`大于一个epoch导致他还没有进行validation，您可以尝试调高epoch或者调低`check_per_step`/`check_per_epoch`。

**Comment by shannon-paul** [comment]
> 您好，
> 
> 非常感谢您对我们提出的宝贵建议，这里面的`best_model_path`是pytorch_lightning框架中封装好的用法，用来检索最佳checkpoint的路径，所以在main.py里面用`best_model_path`是没问题的，dirpath只是checkpoint所在的目录路径。您在跑一个epoch的时候`model_checkpoint.best_model_path`是空值是因为脚本里面的`check_per_step`/`check_per_epoch`大于一个epoch导致他还没有进行validation，您可以尝试调高epoch或者调低`check_per_step`/`check_per_epoch`。

确实是epoch过小导致的，感谢作者的回答 :)👍
