### ISSUE TITLE
请问脚本文件夹中有的脚本有v1v2等不同版本，内容只是指定的GPU不同

### ISSUE THREAD

**Issue by shannon-paul** [zjukg/NeuralKG#39]
![image](https://github.com/zjukg/NeuralKG/assets/56437396/e5d5f75f-eebe-424b-aaf6-db624e352f72)
如图所示，为什么要这样呢，有什么作用吗

**Comment by hzwy3c** [comment]
您好，

v1到v4是FB15K237数据集中不同的四个子集，运行脚本里面的`DATASET_NAME`也不同。

附论文[Inductive Relation Prediction by Subgraph Reasoning](https://arxiv.org/abs/1911.06962)中列出来的inductive benchmark datasets的数据：
<img width="1413" alt="image" src="https://github.com/zjukg/NeuralKG/assets/57245981/83807a1c-b884-49ec-aac4-5f073537713b">
