### ISSUE TITLE
请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！

### ISSUE THREAD

**Issue by mamajungithub** [zjukg/NeuralKG#44]

**Comment by hzwy3c** [comment]
您好，

pytorch版本为1.12.1，dgl版本为0.9.1，pytorch-lightning版本为1.5.10。版本过高可能会出现不兼容问题，所以最好按照参考版本下载。

**Comment by mamajungithub** [comment]
谢谢老师，请问这方面有你们有著作没？想好好研究，向你们好好学习



---原始邮件---
发件人: "Zhiwei ***@***.***&gt;
发送时间: 2024年3月27日(周三) 中午12:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)




 
您好，
 
pytorch版本为1.12.1，dgl版本为0.9.1，pytorch-lightning版本为1.5.10。版本过高可能会出现不兼容问题，所以最好按照参考版本下载。

**Comment by hzwy3c** [comment]
非常感谢您对我们工作的支持和兴趣！我们很高兴能够为您提供我们的论文地址：

NeuralKG: An Open Source Library for Diverse Representation Learning of Knowledge Graphs
您可以在以下链接找到这篇工作：https://arxiv.org/abs/2202.12571

NeuralKG-ind: A Python Library for Inductive Knowledge Graph Representation Learning
这篇工作的链接在这里：https://arxiv.org/abs/2304.14678

希望这些能对您的研究有所帮助。如果您对其中任何内容有任何疑问或需要进一步的解释，请随时告诉我们。再次感谢您的关注！

**Comment by mamajungithub** [comment]
非常感谢！我也是一个教学工作者，我的微信号是junjun255422，手机号13384930881，对您的研究和成果特别感兴趣，如果方便加一下微信，以后方便向您请教



---原始邮件---
发件人: "Zhiwei ***@***.***&gt;
发送时间: 2024年3月27日(周三) 中午1:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)




 
非常感谢您对我们工作的支持和兴趣！我们很高兴能够为您提供我们的论文地址：
 
NeuralKG: An Open Source Library for Diverse Representation Learning of Knowledge Graphs
 您可以在以下链接找到这篇工作：https://arxiv.org/abs/2202.12571
 
NeuralKG-ind: A Python Library for Inductive Knowledge Graph Representation Learning
 这篇工作的链接在这里：https://arxiv.org/abs/2304.14678
 
希望这些能对您的研究有所帮助。如果您对其中任何内容有任何疑问或需要进一步的解释，请随时告诉我们。再次感谢您的关注！

**Comment by mamajungithub** [comment]
老师您好，我下载不到您指定的版本啊，我在Autodl里面运行，gpu为3090,因为4090只能用更新的cuda






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/NeuralKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 中午1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)





 
非常感谢您对我们工作的支持和兴趣！我们很高兴能够为您提供我们的论文地址：
 
NeuralKG: An Open Source Library for Diverse Representation Learning of Knowledge Graphs
 您可以在以下链接找到这篇工作：https://arxiv.org/abs/2202.12571
 
NeuralKG-ind: A Python Library for Inductive Knowledge Graph Representation Learning
 这篇工作的链接在这里：https://arxiv.org/abs/2304.14678
 
希望这些能对您的研究有所帮助。如果您对其中任何内容有任何疑问或需要进一步的解释，请随时告诉我们。再次感谢您的关注！

**Comment by mamajungithub** [comment]
能不能给个详细的指导，在colab上的demo也无法运行了，麻烦您了，先感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/NeuralKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 中午1:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)





 
非常感谢您对我们工作的支持和兴趣！我们很高兴能够为您提供我们的论文地址：
 
NeuralKG: An Open Source Library for Diverse Representation Learning of Knowledge Graphs
 您可以在以下链接找到这篇工作：https://arxiv.org/abs/2202.12571
 
NeuralKG-ind: A Python Library for Inductive Knowledge Graph Representation Learning
 这篇工作的链接在这里：https://arxiv.org/abs/2304.14678
 
希望这些能对您的研究有所帮助。如果您对其中任何内容有任何疑问或需要进一步的解释，请随时告诉我们。再次感谢您的关注！

**Comment by hzwy3c** [comment]
方便具体给出是哪个下载不到指定版本吗，如果是dgl可以参考dgl官网：https://www.dgl.ai/pages/start.html，pytorch可以参考pytorch官网：https://pytorch.org/，另外更换镜像源也是一种方案。

colab上的demo报错能给出具体报错信息吗，这里也有其他的comment可做参考： #40 #25 #21

**Comment by hzwy3c** [comment]
方便具体给出是哪个下载不到指定版本吗，如果是dgl可以参考[dgl官网](https://www.dgl.ai/pages/start.html)，pytorch可以参考[pytorch官网](https://pytorch.org/)，另外更换镜像源也是一种方案。

colab上的demo报错能给出具体报错信息吗，这里也有其他的comment可做参考： #40 #25 #21

**Comment by mamajungithub** [comment]
您给我指导的是用上图中的几个版本，但是我安装的时候安装不了，请看图





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/NeuralKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 中午12:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)





 
您好，
 
pytorch版本为1.12.1，dgl版本为0.9.1，pytorch-lightning版本为1.5.10。版本过高可能会出现不兼容问题，所以最好按照参考版本下载。

**Comment by mamajungithub** [comment]
在colab上调整版本后，后面无法运行，





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/NeuralKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)





 
方便具体给出是哪个下载不到指定版本吗，如果是dgl可以参考dgl官网，pytorch可以参考pytorch官网，另外更换镜像源也是一种方案。
 
colab上的demo报错能给出具体报错信息吗，这里也有其他的comment可做参考： #40 #25 #21

**Comment by mamajungithub** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/NeuralKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)





 
方便具体给出是哪个下载不到指定版本吗，如果是dgl可以参考dgl官网，pytorch可以参考pytorch官网，另外更换镜像源也是一种方案。
 
colab上的demo报错能给出具体报错信息吗，这里也有其他的comment可做参考： #40 #25 #21

**Comment by mamajungithub** [comment]
能加一下微信吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjukg/NeuralKG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月27日(星期三) 下午3:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjukg/NeuralKG] 请问贵楼主，必须使用哪个版本的pytorch和dgl，我在云算力上配置一致出问题，能不能给个详细的指导，谢谢！ (Issue #44)





 
方便具体给出是哪个下载不到指定版本吗，如果是dgl可以参考dgl官网，pytorch可以参考pytorch官网，另外更换镜像源也是一种方案。
 
colab上的demo报错能给出具体报错信息吗，这里也有其他的comment可做参考： #40 #25 #21

**Comment by hzwy3c** [comment]
我这边看不到您发的图，已经加您微信了～
