### ISSUE TITLE
Inquiries about code issues

### ISSUE THREAD

**Issue by forgetlove123** [zjukg/NeuralKG#45]
Hello, I was browsing on github for the open source library on knowledge graph for diverse representation learning(NeuralKG).It demonstrates a demo about knowledge questions and answers on github.I encountered a problem about multithreading when debugging the code of the demo locally, and the specific problem is shown in the following figure:
![Uploading QQ截图20240412202145.png…]()

Local runtime environment:
win11,torch2.12.1+cu116

**Comment by forgetlove123** [comment]
ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ArgumentParser.__init__.<locals>.identity'

**Comment by hzwy3c** [comment]
Thank you very much for your attention and use. Unfortunately, I can't view the screenshot you uploaded, but based on the information you provided, it seems like it might be related to the issue mentioned in https://github.com/kevlened/pytest-parallel/issues/74. It's possible that on Windows systems, the absence of ForkingPickler is causing this error.

You can try setting it manually to "forkserver" as suggested in https://github.com/kevlened/pytest-parallel/issues/41:

> So you could set it manually to "forkserver" I guess.
`import multiprocessing as mp; mp.set_start_method("forkserver")`
> 
Hope this helps you resolve the issue!

>
