### ISSUE TITLE
我可以使用不同的打分函数吗

### ISSUE THREAD

**Issue by zhangxy22** [zjukg/NeuralKG#47]
因为代码能力很low所以我想在这个上面调试se-gnn的模型但是不知道能否满足我的需求，使用不同的打分函数可以实现吗

**Comment by hzwy3c** [comment]
你好，

感谢你对我们工作的关注。你可以在[src/neuralkg/model/GNNModel/SEGNN.py](https://github.com/zjukg/NeuralKG/blob/main/src/neuralkg/model/GNNModel/SEGNN.py)中更改predictor，现在默认使用的是ConvE。如果你想使用不同的打分函数，可以在src/neuralkg/model/KGEModel目录下找到其他的打分函数并进行替换。

希望这能满足你的需求！

**Comment by zhangxy22** [comment]
但是参数传递不一样我很难修改（😭）

在 2024-06-01 21:08:03，Zhiwei Huang ***@***.***> 写道：

你好，
感谢你对我们工作的关注。你可以在src/neuralkg/model/GNNModel/SEGNN.py中更改predictor，现在默认使用的是ConvE。如果你想使用不同的打分函数，可以在src/neuralkg/model/KGEModel目录下找到其他的打分函数并进行替换。
希望这能满足你的需求！

**Comment by hzwy3c** [comment]
目标都是通过三元组中的head_emb, relation_emb, tail_emb计算得分。

只不过在SEGNN中计算的是head(batch_size * emb_dim)、relation(batch_size * emb_dim)和所有尾实体(num_entity * emb_dim)的得分，最终输出是各个三元组的得分(batch_size * num_enttity)。

为了对齐可以在这部份修改成和每个尾实体分别计算得分，或者将h，r，t的维度分别改成(batch_size * 1 * emb_dim)，(batch_size * 1 * emb_dim)，(1 * num_entity * emb_dim)进行计算，这可以参考src/neuralkg/model/KGEModel/model.py中的tri2emb

**Comment by zhangxy22** [comment]
非常感谢您的回复这对我至关重要，无以言表我给您磕一个吧，下次不这么轻易打扰您了

在 2024-06-01 21:45:32，Zhiwei Huang ***@***.***> 写道：

目标都是通过三元组中的head_emb, relation_emb, tail_emb计算得分。
只不过在SEGNN中计算的是head(batch_size * emb_dim)、relation(batch_size * emb_dim)和所有尾实体(num_entity * emb_dim)的得分，最终输出是各个三元组的得分(batch_size * num_enttity)。
为了对齐可以在这部份修改成和每个尾实体分别计算得分，或者将h，r，t的维度分别改成(batch_size * 1 * emb_dim)，(batch_size * 1 * emb_dim)，(1 * num_entity * emb_dim)进行计算，这可以参考src/neuralkg/model/KGEModel/model.py中的tri2emb

**Comment by hzwy3c** [comment]
不必客气，有任何问题随时提问，我们都很乐意帮助你。

**Comment by zhangxy22** [comment]
作为一个小白我此时此刻感动的都要哭了，只求我能顺利毕业谢谢您大好人

在 2024-06-01 21:49:20，Zhiwei Huang ***@***.***> 写道：

不必客气，有任何问题随时提问，我们都很乐意帮助你。

**Comment by zhangxy22** [comment]
您好，深夜打扰到您我最近想用一些三元组的嵌入模型输出作为se-gnn模型的初始化嵌入，但是我没有找到别人运行代码后提取到的嵌入，不知道有没有这种渠道。
这里的一些三元组的嵌入模型输出是指比如TransE等这种模型的输出嵌入。






发件人：Zhiwei Huang ***@***.***>
发送日期：2024-06-01 21:49:20
收件人：zjukg/NeuralKG ***@***.***>
抄送人：zxy ***@***.***>,Author ***@***.***>
主题：Re: [zjukg/NeuralKG] 我可以使用不同的打分函数吗 (Issue #47)

不必客气，有任何问题随时提问，我们都很乐意帮助你。

**Comment by hzwy3c** [comment]
非常抱歉回复得这么晚，希望还能帮助到你。

以TransE为例，我们可以训练TransE模型并将训练好的实体和关系embedding保存到文件中：

```
class TransE(Model):
    # ... (TransE模型的定义)

    def save_embeddings(self, file_path):
        torch.save({
            'ent_emb': self.ent_emb.state_dict(),
            'rel_emb': self.rel_emb.state_dict()
        }, file_path)

# transe_model为训练好的TransE模型
transe_model.save_embeddings('transe_embeddings.pth')
```

之后可以在其他模型的初始化过程中加载这些embedding：
```
class SEGNN(Model):
    def __init__(self, args):
        super(SEGNN, self).__init__()
        self.args = args
        self.ent_emb = nn.Embedding(self.args.num_ent, self.args.emb_dim)
        self.rel_emb = nn.Embedding(self.args.num_rel, self.args.emb_dim)
        self.init_emb()

    def init_emb(self):
        # 加载TransE的嵌入
        checkpoint = torch.load('transe_embeddings.pth')
        self.ent_emb.load_state_dict(checkpoint['ent_emb'])
        self.rel_emb.load_state_dict(checkpoint['rel_emb'])
```

**Comment by zhangxy22** [comment]
是的，但是我想问的是有没有对模型进行整理的pth合集，比如对于fb15k237和wn18rr这两个数据集的模型保存分享，因为我要每个训练的话，比较复杂，在检索有没有整理好的模型，或者是分享

在 2024-06-11 11:17:06，Zhiwei Huang ***@***.***> 写道：

非常抱歉回复得这么晚，希望还能帮助到你。
以TransE为例，我们可以训练TransE模型并将训练好的实体和关系embedding保存到文件中：
class TransE(Model):
    # ... (TransE模型的定义)

    def save_embeddings(self, file_path):
        torch.save({
            'ent_emb': self.ent_emb.state_dict(),
            'rel_emb': self.rel_emb.state_dict()
        }, file_path)

# transe_model为训练好的TransE模型
transe_model.save_embeddings('transe_embeddings.pth')
之后可以在其他模型的初始化过程中加载这些embedding：
class SEGNN(Model):
    def __init__(self, args):
        super(SEGNN, self).__init__()
        self.args = args
        self.ent_emb = nn.Embedding(self.args.num_ent, self.args.emb_dim)
        self.rel_emb = nn.Embedding(self.args.num_rel, self.args.emb_dim)
        self.init_emb()

    def init_emb(self):
        # 加载TransE的嵌入
        checkpoint = torch.load('transe_embeddings.pth')
        self.ent_emb.load_state_dict(checkpoint['ent_emb'])
        self.rel_emb.load_state_dict(checkpoint['rel_emb'])

**Comment by hzwy3c** [comment]
了解。这个我也不太清楚有没有直接可用的模型，但是像TransE模型，在FB15K237和WN18RR这样的数据集上如果自己训练起来的话也是很快的。

**Comment by zhangxy22** [comment]
是的，我有transe模型的pth，但是想尝试更多的模型作为初始化嵌入。因为有些模型参数比较大我训练不了，谢谢您！

在 2024-06-11 11:54:30，Zhiwei Huang ***@***.***> 写道：

了解。这个我也不太清楚有没有直接可用的模型，但是像TransE模型，在FB15K237和WN18RR这样的数据集上如果自己训练起来的话也是很快的。
