### ISSUE TITLE
大规模KG的训练

### ISSUE THREAD

**Issue by AprLie** [zjukg/NeuralKG#9]
Hi，

请问NeuralKG是否支持大规模KG的训练，如ogb的wikikg90m数据集？

**Comment by wencolani** [comment]
你好，NeuralKG中的KGE模型都是可以用于大规模数据集如ogb的训练的，但需要硬件资源满足需求。

**Comment by AprLie** [comment]
我测试时候发现NeuralKG不支持多卡训练，在加载数据时也直接就被Kill（硬件资源充足的情况）

**Comment by Modberge** [comment]
> 我测试时候发现NeuralKG不支持多卡训练，在加载数据时也直接就被Kill（硬件资源充足的情况）

您好，NeuralKG是基于Pytorch_lightning构建的KGE训练框架，您可以参考Pytorch_lightning官方的[多卡训练教程](https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu_intermediate.html?highlight=muti-GPU#distributed-data-parallel)来自定义trainer函数进行多卡训练。
